# Build & Deploy .NET 8 app to Azure App Service (OIDC login)
name: Build and deploy .NET app to Azure Web App - saucallingbot

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write     # required for azure/login (OIDC)
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Restore, Build & Publish (to ./published)
      - name: Restore
        run: dotnet restore ./src/SauCallingBot/SauCallingBot.csproj

      - name: Build
        run: dotnet build ./src/SauCallingBot/SauCallingBot.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./src/SauCallingBot/SauCallingBot.csproj -c Release -o ./published --no-build

      # Login to Azure using the user-assigned identity secrets that Azure created
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E4974B174DBA4B74ACBE4E86FC4B86F6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0158EDAE809648C3AA88F8DD49B9A490 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_079D0419AFFD414FB72C4212AFD70BA6 }}

      # Deploy the published output folder to Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'saucallingbot'
          slot-name: 'Production'
          package: ./published
