name: Build and deploy .NET app to Azure Web App - saucallingbot

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 🔎 Repo లోని .csproj path ను ఆటోమేటిక్‌గా కనుగొనండి
      - name: Show repo tree & find csproj
        id: probe
        shell: bash
        run: |
          echo "PWD=$(pwd)"
          echo "Root listing:"
          ls -la
          echo "----- Searching for *.csproj (maxdepth 5) -----"
          FOUND=$(find . -maxdepth 5 -type f -name "*.csproj" | head -n 1)
          if [ -z "$FOUND" ]; then
            echo "No .csproj found!"; exit 1
          fi
          echo "Found project: $FOUND"
          echo "PROJECT_PATH=$FOUND" >> $GITHUB_OUTPUT

      - name: Restore
        run: dotnet restore "${{ steps.probe.outputs.PROJECT_PATH }}"

      - name: Build
        run: dotnet build "${{ steps.probe.outputs.PROJECT_PATH }}" --configuration Release --no-restore

      - name: Publish
        run: |
          OUT="./published"
          dotnet publish "${{ steps.probe.outputs.PROJECT_PATH }}" -c Release -o "$OUT" --no-build
          echo "Published to $OUT"

      # ✅ Publish Profile తో సింపుల్‌గా deploy
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'saucallingbot'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./published

